# Generated by Django 4.1.3 on 2022-11-26 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
