# Generated by Django 4.1.3 on 2022-11-30 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_director_image'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='anime',
            order_with_respect_to='director',
        ),
    ]
