# Generated by Django 4.1.3 on 2022-11-30 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0003_alter_anime_order_with_respect_to'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='anime',
            order_with_respect_to=None,
        ),
    ]
