# Generated by Django 4.1.3 on 2022-12-01 16:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anime', '0004_alter_anime_order_with_respect_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='viewers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
