# Generated by Django 4.1.3 on 2022-12-07 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0005_anime_viewers'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='description',
            field=models.CharField(max_length=3000, null=True),
        ),
    ]
